import '@/styles/globals.css'

import { type Metadata } from 'next'
import { Geist } from 'next/font/google'

import { getLocale } from '@/i18n/server'
import type { ILayout } from '@/types'
import { I18nProvider } from '@/i18n/provider'
import { ThemeProvider } from 'next-themes'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const geist = Geist({ subsets: ['latin'], variable: '--font-geist-sans' })

export default async function RootLayout({ children }: ILayout) {
  const locale = await getLocale()

  return (
    <html lang={locale} className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          storageKey="theme"
          disableTransitionOnChange
        >
          <I18nProvider locale={locale}>{children}</I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
